concurrent = 100

[[runners]]
  url = "https://gitlab.com/ci"
  token = "{{ gitlab_ci_runner_token }}"
  name = "docker-remote-runner"
  limit = 0
  executor = "docker"
  [runners.docker]
    image = "{{ docker_image }}"
    host = "http://{{ groups['slave'][0] }}:2375"
    privileged = true
    tls_cert_path = "/root/.docker"
    disable_cache = true
    links = ["dind:docker"]
